### ISSUE TITLE
Support Debians Ayatana Indicators

### ISSUE THREAD

**Issue by worldofpeace** [elementary/wingpanel-indicator-ayatana#18]
* https://github.com/AyatanaIndicators/libayatana-indicator

They're being maintained and the primary goal is for the indicators to work in as many distros as possible. This would simplify packaging efforts as well.

**Comment by cassidyjames** [comment]
Considering that this project is effectively abandoned, I don't see reviving it any time soon. See: https://github.com/elementary/wingpanel/issues/96

**Comment by worldofpeace** [comment]
Wish I saw that two days ago :(

**Comment by worldofpeace** [comment]
Shouldn't this repo be archived then?
